# Generated by Django 6.0.2 on 2026-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaillyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='filme', max_length=80)),
                ('filme', models.FileField(upload_to='filmes/')),
                ('data', models.CharField(default='02 fev 2024', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Momentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='momento', max_length=80)),
                ('momento', models.CharField(default='um momento especial na minha vida', max_length=3000)),
                ('data', models.CharField(default='02 fev 2024', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha serie', max_length=80)),
                ('data', models.CharField(default='02 fev 2024', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='temporada 1', max_length=80)),
                ('data', models.CharField(default='02 fev 2024', max_length=20)),
                ('episodio_filme', models.ManyToManyField(blank=True, to='DaillyApp.filmes')),
                ('episodio_momento', models.ManyToManyField(blank=True, to='DaillyApp.momentos')),
            ],
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Dados',
        ),
        migrations.AddField(
            model_name='serie',
            name='temporada',
            field=models.ManyToManyField(to='DaillyApp.temporada'),
        ),
    ]
